spring:
  application:
    name: router4j-server

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

router4j:
  redis:
    host: localhost
    password: 222333
    port: 6379
    # database: 0
    # ssl: false
    # timeout: 3s
  rule:
    enable: true
    # prefix: "router4j:rule:prefix:"