server:
  port: 9013

spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true