server:
  port: 6001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 解析微服务名称为主机名和端口，实现动态路由
          enabled: true
          # 服务名使用小写
          lower-case-service-id: true
    nacos:
      discovery:
        server-addr: localhost:8848

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug

